//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selling
    {
        public int Id { get; set; }
        public int Id_product { get; set; }
        public int Id_seller { get; set; }
        public int Number { get; set; }
        public decimal Price { get; set; }
        public System.DateTime datetime { get; set; }
        public string Status { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
