//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presence
    {
        public int Id { get; set; }
        public int Id_shop { get; set; }
        public int Id_product { get; set; }
        public bool Receive { get; set; }
        public string Accounting_date { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
